// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdAIEHtA5RJaqCnh8GPAO2WNt5EEdbRx0',
    appId: '1:168320255818:web:62b37228cad9d8534d23b3',
    messagingSenderId: '168320255818',
    projectId: 'matrimonial-app-7aa7a',
    authDomain: 'matrimonial-app-7aa7a.firebaseapp.com',
    storageBucket: 'matrimonial-app-7aa7a.firebasestorage.app',
    measurementId: 'G-D2M8GFQ9HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqgeVoMPHLg_N9m1dMt3X_OdSqei23pM',
    appId: '1:168320255818:android:5dabca9d3756e0d24d23b3',
    messagingSenderId: '168320255818',
    projectId: 'matrimonial-app-7aa7a',
    storageBucket: 'matrimonial-app-7aa7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbvQMP5xk9KEkjcbjzidEfEOpvZjeuPA',
    appId: '1:168320255818:ios:486e3970a8da6e3b4d23b3',
    messagingSenderId: '168320255818',
    projectId: 'matrimonial-app-7aa7a',
    storageBucket: 'matrimonial-app-7aa7a.firebasestorage.app',
    iosBundleId: 'com.example.matrimonialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbvQMP5xk9KEkjcbjzidEfEOpvZjeuPA',
    appId: '1:168320255818:ios:486e3970a8da6e3b4d23b3',
    messagingSenderId: '168320255818',
    projectId: 'matrimonial-app-7aa7a',
    storageBucket: 'matrimonial-app-7aa7a.firebasestorage.app',
    iosBundleId: 'com.example.matrimonialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdAIEHtA5RJaqCnh8GPAO2WNt5EEdbRx0',
    appId: '1:168320255818:web:d52edc7f48c6b66b4d23b3',
    messagingSenderId: '168320255818',
    projectId: 'matrimonial-app-7aa7a',
    authDomain: 'matrimonial-app-7aa7a.firebaseapp.com',
    storageBucket: 'matrimonial-app-7aa7a.firebasestorage.app',
    measurementId: 'G-05695FPY2L',
  );
}
